/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.x19990416.mxpaas.admin;

import com.github.x19990416.mxpaas.admin.common.annotation.controller.AnonymousGetMapping;
import com.github.x19990416.mxpaas.admin.common.utils.SpringContextHolder;
import io.swagger.annotations.Api;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import org.springframework.boot.web.servlet.server.ServletWebServerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.bind.annotation.RestController;
@EnableAsync
@RestController
@Api(hidden = true)
@SpringBootApplication
@EnableTransactionManagement
//@EnableJpaAuditing(auditorAwareRef = "auditorAware")
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  @Bean
  public SpringContextHolder springContextHolder() {
    return new SpringContextHolder();
  }

  @Bean
  public ServletWebServerFactory webServerFactory() {
    TomcatServletWebServerFactory tfa = new TomcatServletWebServerFactory();
    tfa.addConnectorCustomizers(connector -> connector.setProperty("relaxedQueryChars", "[]{}"));
    return tfa;
  }

  /**
   * 访问首页提示
   *
   * @return /
   */
  @AnonymousGetMapping(value = "/123")
  public String index() {
    return "Backend service started successfully";
  }
}
